---
- hosts: servers
  become: true
  tasks:
  - name: Date in Ansible
    debug:
      var=ansible_date_time.date
  - name: Time in Ansible
    debug:
      var=ansible_date_time.time
      