---
- hosts: crunchify
  become: yes
 
  pre_tasks:
     - raw: sudo apt-get -y install python-simplejson
       register: py_simple_output
     - raw: sudo apt-get -y install python-minimal
       register: py_minimal_output
     - raw: sudo apt-get update
       register: system_output
     - raw: sudo apt-get install -y default-jre
       register: java_output
 
  tasks:
  
    - debug: 
        var=py_simple_output.stdout_lines
 
    - debug: 
        var=py_minimal_output.stdout_lines
 
    - debug: 
        var=system_output.stdout_lines
 
    - debug: 
        var=java_output.stdout_lines
 
    - name: get Python version
      shell: python --version 2>&1
      register: py_output
    
    - debug: 
        var=py_output.stdout_lines
      
    - name: get Java version
      shell: java --version 2>&1
      register: java_output
    
    - debug: 
        var=java_output.stdout_lines